//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityGate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolledCours
    {
        public int enrollment_id { get; set; }
        public int student_id { get; set; }
        public int course_id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
