//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityGate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int grade_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<decimal> grade_value { get; set; }
        public Nullable<int> professor_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
